name: Reusable prisma migration generation workflow

on:
  workflow_call:
    inputs:
      DEPLOYMENT_PREFIX:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      ORG_NAME:
        required: true
        type: string
      DATABASE:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      PACKAGES_TOKEN:
        required: true
      PRIVATE_REPO_WRITER:
        required: true

jobs:
  prisma-create-and-pr-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Installing AWS CLI
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create .npmrc
        uses: FerLuisxd/create-npmrc@3
        with:
          org_name: ${{ inputs.ORG_NAME }}
        env:
          AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Get SSM DB Connection String
        run: |
          echo "Generating SSM Name..."
          ENVIRONMENT=${{ inputs.ENVIRONMENT }}
          DEPLOYMENT_PREFIX=${{ inputs.DEPLOYMENT_PREFIX }}
          DATABASE=${{ inputs.DATABASE }}
          SSM_NAME=/${ENVIRONMENT}/${DEPLOYMENT_PREFIX}/APPLICATION_POSTGRES_${DATABASE}_DB_MIGRATOR_CONNECTION_STRING
          echo $SSM_NAME

          echo "Retrieving SSM DB Connection String..."
          DATABASE_CONNECTION_STRING="$(aws ssm get-parameter --name $SSM_NAME --with-decryption | jq -r '.Parameter.Value')"
          echo "::set-output name=CONNECTION_STRING::$DATABASE_CONNECTION_STRING"
        id: DB

      - name: Checkout Migrations Repo
        uses: actions/checkout@v3
        with:
          repository: Pantomath-Dev/${{ inputs.ENVIRONMENT }}-database-migrations
          token: ${{ secrets.PRIVATE_REPO_WRITER }} # Owned by Joe
          path: ${{ inputs.ENVIRONMENT }}-database-migrations

      - name: Generate and Output Lowercase DB Name
        run: |
          echo "Generating lowercase DB name..."
          LOWERCASE_DATABASE_NAME=$(echo 'console.log("${{ inputs.DATABASE }}".toLowerCase())' | node -);
          echo "::set-output name=LOWERCASE_DATABASE_NAME::$LOWERCASE_DATABASE_NAME"
        id: LOWERCASE-DATABASE

      - name: Retrieve Migration Repo Hash
        run: |
          echo "Generating repo hash..."
          cd ./${{ inputs.ENVIRONMENT }}-database-migrations
          HASH=$(git rev-parse HEAD);
          echo "::set-output name=HASH::$HASH"
          cd ../
        id: MIGRATION-REPO-HASH

      - name: Wait for Prisma Apply to Succeed if Running
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          token: ${{ secrets.PRIVATE_REPO_WRITER }} # Owned by Joe
          checkName: invoke-default-prisma-migrate-deploy-workflow
          repo: ${{ inputs.ENVIRONMENT }}-database-migrations
          ref: ${{ steps.MIGRATION-REPO-HASH.outputs.HASH }}
        id: WAIT-FOR-BUILD

      - name: Install Dependencies & Create Migration
        run: |
          echo "Setting DB Connection String..."
          APPLICATION_POSTGRES_CONNECTION_STRING=${{ steps.DB.outputs.CONNECTION_STRING }}

          echo "Saving DB Connection String to .env file..."
          echo "APPLICATION_POSTGRES_CONNECTION_STRING"=$APPLICATION_POSTGRES_CONNECTION_STRING >> ".env"

          echo "Copy old migrations from migration repo to repo migrations folder"
          mkdir -p ./prisma/migrations
          mkdir -p ./${{ inputs.ENVIRONMENT }}-database-migrations/${{ steps.LOWERCASE-DATABASE.outputs.LOWERCASE_DATABASE_NAME }}/prisma/migrations
          cp -a ./${{ inputs.ENVIRONMENT }}-database-migrations/${{ steps.LOWERCASE-DATABASE.outputs.LOWERCASE_DATABASE_NAME }}/prisma/migrations ./prisma/.

          echo "Clean runnings..."
          npm run clean

          echo "Creating Prisma migration against proper database..."
          npm run prisma-create-migration -- --name migration

          echo "Retrieving the name of the new migration and outputing..."
          cd ./prisma/migrations 
          NEW_MIGRATION_NAME="$(ls -Art | tail -n 1)"
          echo "::set-output name=NEW_MIGRATION_NAME::$NEW_MIGRATION_NAME"
          cd ../../
        id: CREATE-MIGRATION

      - name: Copy Migrations to the Proper DB Migration Repo
        run: |
          echo "Copy generated migrations to proper db migrations repo and folder"
          mkdir -p ./${{ inputs.ENVIRONMENT }}-database-migrations/${{ steps.LOWERCASE-DATABASE.outputs.LOWERCASE_DATABASE_NAME }}/prisma/migrations
          cp -a ./prisma/schema.prisma ./${{ inputs.ENVIRONMENT }}-database-migrations/${{ steps.LOWERCASE-DATABASE.outputs.LOWERCASE_DATABASE_NAME }}/prisma
          cp -a ./prisma/migrations/. ./${{ inputs.ENVIRONMENT }}-database-migrations/${{ steps.LOWERCASE-DATABASE.outputs.LOWERCASE_DATABASE_NAME }}/prisma/migrations/

          echo "Navigating to ${{ inputs.ENVIRONMENT }}-database-migrations directory"
          tree ${{ inputs.ENVIRONMENT }}-database-migrations

      - name: Get Current Date to Append to Branch Name
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        id: DATE

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PRIVATE_REPO_WRITER }}
          commit-message: Creating new migration ${{ steps.CREATE-MIGRATION.outputs.NEW_MIGRATION_NAME }} for ${{ steps.LOWERCASE-DATABASE.outputs.LOWERCASE_DATABASE_NAME }} DB
          branch: new-${{ steps.LOWERCASE-DATABASE.outputs.LOWERCASE_DATABASE_NAME }}-db-migration
          title: new-${{ steps.LOWERCASE-DATABASE.outputs.LOWERCASE_DATABASE_NAME }}-db-migration
          path: ${{ inputs.ENVIRONMENT }}-database-migrations
          committer: Github Actions Bot <githubactionsbot@pantomathglobal.com>
          author: Github Actions Bot <githubactionsbot@pantomathglobal.com>
