name: Reusable lint and test workflow

on:
  workflow_call:
    inputs:
      ORG_NAME:
        required: true
        type: string
    secrets:
      PACKAGES_TOKEN:
        required: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create .npmrc
        uses: FerLuisxd/create-npmrc@3
        with:
          org_name: ${{ inputs.ORG_NAME }}
        env:
          AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Optionally Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm install

      - name: Optionally Generate Prisma Client(s)
        if: ${{ secrets.GENERATE_PRISMA_CLIENT }} == 'true'
        run: npm run prisma-generate-clients

      - name: Lint & Test
        run: |
          npm run lint
          npm test
